name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create PDF
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: MiniFate
        path: ./MiniFate.pdf
